version: '3.8'

services:
  web:
    build: .
    command: gunicorn djangoProjectKh.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/usr/app/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/usr/app/staticfiles/
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_volume: