# Generated by Django 5.0.7 on 2024-07-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableStock",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("party_sign", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buying_season",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("division", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "line_of_business",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("available", models.FloatField()),
            ],
            options={
                "db_table": "available_stock",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClientContract",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("client", models.UUIDField(blank=True, null=True)),
                ("contract", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_contract",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClientGuide",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("client", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_guide",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ContractProduct",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("contract", models.UUIDField(blank=True, null=True)),
                ("product", models.CharField(blank=True, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("in_delivery", models.BooleanField()),
            ],
            options={
                "db_table": "contract_product",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("contract_supplement", models.CharField(blank=True, null=True)),
                ("product", models.CharField(blank=True, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("manager", models.CharField(blank=True, null=True)),
                ("client", models.CharField(blank=True, null=True)),
                ("quantity_delivery", models.FloatField(blank=True, null=True)),
                ("date_delivery", models.DateField(blank=True, null=True)),
                ("proove", models.BooleanField(blank=True, null=True)),
                ("key", models.CharField(blank=True, null=True)),
                ("delivery_manager_key", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "delivery",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "documents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GuideContract",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("contract", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "guide_contract",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ManagerClient",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("manager", models.UUIDField(blank=True, null=True)),
                ("client", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "manager_client",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ManagerGuideTable",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("manager", models.CharField(blank=True, null=True)),
                ("manager_email", models.CharField(blank=True, null=True)),
                ("role", models.CharField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "manager_guide_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MovedData",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=255)),
                ("contract", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField()),
                ("line_of_business", models.CharField(max_length=255)),
                ("qt_order", models.CharField(max_length=255)),
                ("qt_moved", models.CharField(max_length=255)),
                ("party_sign", models.CharField(max_length=255)),
                ("period", models.CharField(max_length=255)),
                ("order", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "moved_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("client", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrdersForDelivery",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("manager", models.CharField(blank=True, null=True)),
                ("client", models.CharField(blank=True, null=True)),
                ("contract", models.CharField(blank=True, null=True)),
                ("product", models.CharField(blank=True, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("quantity_in_contract", models.FloatField(blank=True, null=True)),
                ("document", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders_for_delivery",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("contract_supplement", models.CharField(max_length=255)),
                ("contract_type", models.CharField(max_length=255)),
                ("prepayment_amount", models.FloatField()),
                ("amount_of_credit", models.FloatField()),
                ("prepayment_percentage", models.FloatField()),
                ("loan_percentage", models.FloatField()),
                ("planned_amount", models.FloatField()),
                ("actual_sale_amount", models.FloatField()),
                ("actual_payment_amount", models.FloatField()),
                ("planned_amount_excluding_vat", models.FloatField()),
            ],
            options={
                "db_table": "payment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductGuide",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=255, unique=True)),
                (
                    "line_of_business",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "active_substance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "product_guide",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductUnderSubmissions",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("quantity", models.FloatField()),
            ],
            options={
                "db_table": "product_under_submissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Remains",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("line_of_business", models.CharField(max_length=255)),
                ("warehouse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "parent_element",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("party_sign", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buying_season",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nomenclature_series",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mtn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "origin_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "germination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("crop_year", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "quantity_per_pallet",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "active_substance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "certificate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "certificate_start_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "certificate_end_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("buh", models.FloatField()),
                ("skl", models.FloatField()),
                ("weight", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "remains",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Submissions",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("division", models.CharField(blank=True, max_length=255, null=True)),
                ("manager", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("client", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contract_supplement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parent_element",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "active_ingredient",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("party_sign", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buying_season",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "line_of_business",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("period", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "shipping_warehouse",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "delivery_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transport", models.CharField(blank=True, max_length=255, null=True)),
                ("plan", models.FloatField()),
                ("fact", models.FloatField()),
                ("different", models.FloatField()),
            ],
            options={
                "db_table": "submissions",
                "managed": False,
            },
        ),
    ]
