name: CD

on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASS}}
          script: |
#            eval "$(ssh-agent)"
#            ssh-add ~/.ssh/id_rsa
            cd ${{  secrets.PROJECT_PATH }}
            git pull origin main
            docker-compose rm -sf
            docker-compose -f docker-compose.prod.yaml up --build -d
#            docker-compose up -d
            docker image prune -af